// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/utils/Create2.sol";
import "@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol";
import {UUPSUpgradeable} from "@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol";
import {AccessControlUpgradeable} from "@openzeppelin/contracts-upgradeable/access/AccessControlUpgradeable.sol";
import "./SimpleAccount.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";

/**
 * @title SimpleAccountFactory
 * @notice Factory contract for smart accounts.
 * @dev A UserOperations "initCode" holds the address of the factory, and a method call (to createAccount, in this sample factory).
 * The factory's createAccount returns the target account address even if it is already installed.
 *
 * ---------- Version 2 ----------
 * - Added createAccountWithSalt and getAccountAddressWithSalt methods to allow for multiple accounts per owner.
 * - Added version() method to allow for versioning.
 * - Use new SimpleAccount implementation.
 *
 * WARNING: when we upgraded this version we did not reinitialize the factory, so the account implementation is still v1
 *
 * ---------- Version 3 ----------
 * - Deploy v3 of SimpleAccount implementation and reinitialize the factory.
 * - Added event ContractReinitialized(uint256 version) to reinitialization of the factory.
 * - Added currentAccountImplementationVersion() method to know current version of the account implementation.
 * - Renamed accountImplementation to accountImplementationV1 to increase clarity.
 * - Added accountImplementationV3 to store the v3 of the smart account implementation contract.
 * - Added b3tr token address, used to check if an account is legacy or not.
 * - Added isLegacyAccount() method to check if an account is legacy or not.
 * - version() returns an integer, instead of a string.
 * - Fixed: createAccountWithSalt() method was using the getAccountAddress() method instead of getAccountAddressWithSalt()
 * - Fixed: emit AccountCreated after the account is created, so the address is not 0
 *
 * WARNING: In order to maintain consistency of legacy account addresses, we added new checks when calculating the address of a smart account.
 * Those checks are needed because changing the implementation address also changes the account address, so we must ensure that
 * all previously created accounts return the address generated by version 1 (V1) of the SimpleAccount implementation.
 * Unfortunately, addresses can be calculated and used to receive assets before they are actually created,
 * so we cannot determine if an account is legacy until it is created. However, one thing we know is that
 * this factory was only used by the X2Earn Applications of VeBetterDAO until V3, whose only purpose is to
 * reward users with B3TR tokens. We use this information as an additional criterion to identify legacy accounts.
 */
contract SimpleAccountFactory is UUPSUpgradeable, AccessControlUpgradeable {
    event AccountCreated(SimpleAccount account, address owner, uint256 salt);
    event ContractReinitialized(uint256 version);

    /// @notice The v1 of the simple account implementation (before any upgrade)
    SimpleAccount public accountImplementationV1;

    /// @notice The new version of the simple account implementation
    SimpleAccount public accountImplementationV3;

    /// @notice The B3TR token used as reward for the users in VeBetterDAO
    IERC20 public b3tr;

    // ---------- Initialization ---------- //

    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor() {
        _disableInitializers();
    }

    /**
     * @dev Get the version of the factory
     * @return the version of the factory
     */
    function version() public pure returns (uint256) {
        return 3;
    }

    function initialize() public initializer {
        __UUPSUpgradeable_init();
        __AccessControl_init();

        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);

        accountImplementationV1 = new SimpleAccount();
    }

    function initializeV3(
        address newImplementationV3,
        address b3trToken
    ) public reinitializer(3) {
        // Store the new implementation address
        accountImplementationV3 = SimpleAccount(payable(newImplementationV3));

        // Set the B3TR token address
        b3tr = IERC20(b3trToken);

        emit ContractReinitialized(3);
    }

    // ---------- Authorizers ---------- //

    /**
     * @dev Authorize the upgrade of the account
     * @param newImplementation the address of the new implementation
     */
    function _authorizeUpgrade(
        address newImplementation
    ) internal virtual override onlyRole(DEFAULT_ADMIN_ROLE) {}

    // ---------- Setters ---------- //

    /**
     * @dev Create an account, and return its address.
     * Returns the address even if the account is already deployed.
     * This method returns an existing account address even after account creation
     *
     * @notice The salt is calculated internally from the owner address,
     * so the same owner will always get the same address.
     *
     * @notice The implementation address to use will be decided by checking if the address is legacy or not
     */
    function createAccount(
        address owner
    ) public returns (SimpleAccount createdAccount) {
        uint256 salt = uint256(uint160(owner));

        // Calculate address with V1 implementation first (same as getAccountAddress)
        address addressGeneratedWithV1 = Create2.computeAddress(
            bytes32(salt),
            keccak256(
                abi.encodePacked(
                    type(ERC1967Proxy).creationCode,
                    abi.encode(
                        address(accountImplementationV1),
                        abi.encodeCall(SimpleAccount.initialize, (owner))
                    )
                )
            )
        );

        // Check if account already exists
        if (addressGeneratedWithV1.code.length > 0) {
            return SimpleAccount(payable(addressGeneratedWithV1));
        }

        // Check if it's a legacy account
        bool isLegacy = isLegacyAccount(addressGeneratedWithV1);

        address implementationToUse = isLegacy
            ? address(accountImplementationV1)
            : address(accountImplementationV3);

        createdAccount = SimpleAccount(
            payable(
                new ERC1967Proxy{salt: bytes32(salt)}(
                    implementationToUse,
                    abi.encodeCall(SimpleAccount.initialize, (owner))
                )
            )
        );

        emit AccountCreated(createdAccount, owner, salt);
    }

    /**
     * @dev Create an account, and return its address.
     * Returns the address even if the account is already deployed.
     * This method returns an existing account address even after account creation
     *
     * @notice The implementation address to use will be decided by checking if
     * the address is legacy or not.
     */
    function createAccountWithSalt(
        address owner,
        uint256 salt
    ) public returns (SimpleAccount createdAccount) {
        // Calculate address with V1 implementation first (same as getAccountAddressWithSalt)
        address addressGeneratedWithV1 = Create2.computeAddress(
            bytes32(salt),
            keccak256(
                abi.encodePacked(
                    type(ERC1967Proxy).creationCode,
                    abi.encode(
                        address(accountImplementationV1),
                        abi.encodeCall(SimpleAccount.initialize, (owner))
                    )
                )
            )
        );

        // Check if account already exists
        if (addressGeneratedWithV1.code.length > 0) {
            return SimpleAccount(payable(addressGeneratedWithV1));
        }

        // Check if it's a legacy account
        bool isLegacy = isLegacyAccount(addressGeneratedWithV1);

        // For legacy accounts, deploy with V1 implementation
        address implementationToUse = isLegacy
            ? address(accountImplementationV1)
            : address(accountImplementationV3);

        createdAccount = SimpleAccount(
            payable(
                new ERC1967Proxy{salt: bytes32(salt)}(
                    implementationToUse,
                    abi.encodeCall(SimpleAccount.initialize, (owner))
                )
            )
        );

        emit AccountCreated(createdAccount, owner, salt);
    }

    // ---------- Getters ---------- //

    /**
     * @dev Calculate the counterfactual address of this account as it would be returned by createAccount()
     *
     * @notice When this contract was upgraded to V3, we had to change the address of the account implementation,
     * so we need to check through different scenarios if the the account is legacy or not.
     * Rules:
     * - We always use the V1 implementation address to calculate the counterfactual address.
     * - We run a few checks though _getImplementationToUse() to determine if the account is legacy or not, which will return the V1 implementation address if it is.
     */
    function getAccountAddress(address owner) public view returns (address) {
        uint256 salt = uint256(uint160(owner));

        // Always calculate with V1 implementation first
        address addressGeneratedWithV1 = Create2.computeAddress(
            bytes32(salt),
            keccak256(
                abi.encodePacked(
                    type(ERC1967Proxy).creationCode,
                    abi.encode(
                        address(accountImplementationV1),
                        abi.encodeCall(SimpleAccount.initialize, (owner))
                    )
                )
            )
        );

        // If it's a legacy account, return the V1 address
        if (isLegacyAccount(addressGeneratedWithV1)) {
            return addressGeneratedWithV1;
        }

        // For new accounts, calculate with V3 implementation
        return
            Create2.computeAddress(
                bytes32(salt),
                keccak256(
                    abi.encodePacked(
                        type(ERC1967Proxy).creationCode,
                        abi.encode(
                            address(accountImplementationV3),
                            abi.encodeCall(SimpleAccount.initialize, (owner))
                        )
                    )
                )
            );
    }

    /**
     * @dev Calculate the counterfactual address of this account as it would be returned by createAccountWithSalt()
     * * Rules:
     * - We always use the V1 implementation address to calculate the counterfactual address.
     * - We run a few checks though _getImplementationToUse() to determine if the account is legacy or not, which will return the V1 implementation address if it is.
     */
    function getAccountAddressWithSalt(
        address owner,
        uint256 salt
    ) public view returns (address) {
        // Always calculate with V1 implementation first
        address addressGeneratedWithV1 = Create2.computeAddress(
            bytes32(salt),
            keccak256(
                abi.encodePacked(
                    type(ERC1967Proxy).creationCode,
                    abi.encode(
                        address(accountImplementationV1),
                        abi.encodeCall(SimpleAccount.initialize, (owner))
                    )
                )
            )
        );

        // If it's a legacy account, return the V1 address
        if (isLegacyAccount(addressGeneratedWithV1)) {
            return addressGeneratedWithV1;
        }

        // For new accounts, calculate with V3 implementation
        return
            Create2.computeAddress(
                bytes32(salt),
                keccak256(
                    abi.encodePacked(
                        type(ERC1967Proxy).creationCode,
                        abi.encode(
                            address(accountImplementationV3),
                            abi.encodeCall(SimpleAccount.initialize, (owner))
                        )
                    )
                )
            );
    }

    /// @notice Returns the current version of the account implementation
    function currentAccountImplementationVersion()
        public
        view
        returns (uint256)
    {
        return
            SimpleAccount(payable(address(accountImplementationV3))).version();
    }

    /**
     * @dev Get the current version of the account implementation
     * @return The current version of the account implementation
     */
    function currentAccountImplementationAddress()
        public
        view
        returns (address)
    {
        return address(accountImplementationV3);
    }

    /**
     * @dev Check if an account is legacy
     * - If the account is deployed we know it is legacy, so V1 implementation address is returned.
     * - If the account is not deployed, we check if it has any balance of B3TR or VET tokens, if it does, we know it is legacy (so V1 implementation address is returned).
     * - Otherwise, we know it is not legacy, and we can use the V3 implementation address to calculate the counterfactual address.
     * @param accountAddress The address to check
     * @return True if the account is legacy, false otherwise
     */
    function isLegacyAccount(
        address accountAddress
    ) public view returns (bool) {
        if (accountAddress.code.length > 0) {
            // For deployed accounts, check if they're using the V1 implementation
            try SimpleAccount(payable(accountAddress)).version() returns (
                uint256 accountVersion
            ) {
                if (accountVersion == 3) {
                    return false;
                }
            } catch {
                // In the V1 implementation, the version() method is not implemented
                // so if the contract is deployed, but this method fails, we know it's legacy
                return true;
            }
        }

        // If not deployed but has B3TR or ETH tokens, consider it legacy
        return
            b3tr.balanceOf(accountAddress) > 0 ||
            address(accountAddress).balance > 0;
    }
}
